### ISSUE TITLE
Nuget package update?

### ISSUE THREAD

**Issue by smoogipoo** [cyotek/Cyotek.Drawing.BitmapFont#14]
Is it possible to get the nuget package updated? We'd like to use the .NET Standard-compatible library in osu!.

**Comment by cyotek** [comment]
Hello,

Sorry about that - I thought I'd pushed it at the time. I've just packaged it fresh and pushed it.

Note that as I'm not hugely familiar with .NET Core yet, and the fact it was such a PITA to get VS2017 to build the darn thing, I've marked this package as pre-release just in case I've screwed something up. Assuming I haven't and it works for you, I'll upversion again without the pre-release suffix as I have found to my displeasure that depending on pre-release packages is another PITA.

Again, apologies for the delay - let me know if you run into any issues with the new package.

Regards;
Richard Moss

**Comment by smoogipoo** [comment]
Hiya!

I've confirmed that the updated package is working perfectly, thanks!
Closing issue.
