### ISSUE TITLE
Cyotek.Drawing.BitmapFont throws NullReferenceException when tries to load .fnt made by Hiero

### ISSUE THREAD

**Issue by rds1983** [cyotek/Cyotek.Drawing.BitmapFont#23]
Hiero is popular tool used to make .fnt: https://github.com/libgdx/libgdx/wiki/Hiero
However it has one trait - it omits outline setting in the begging of the file(i.e. "outline=0").
So Cyotek.Drawing.BitmapFont fails to load such .fnt as it expects this setting to be there.
Sample .fnt is attached.
[Arial.zip](https://github.com/cyotek/Cyotek.Drawing.BitmapFont/files/5757306/Arial.zip)

**Comment by cyotek** [comment]
Hello,

Thanks for the bug report and especially for the file which reproduced the issue.

I've pushed v2.0.1 with a fix for this.

Regards;
Richard Moss

**Comment by rds1983** [comment]
cool, thanks for the fix!
