### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by cyotek** [cyotek/Cyotek.Drawing.BitmapFont#4]
Add XML documentation comments, I think I saw only a bare handful. API is fairly simple but no excuse not to have them really.

**Comment by miaodadao** [comment]
XML document is useful on NuGet. Please add it.

**Comment by cyotek** [comment]
Hello,

I've just uploaded version 1.3.0 which includes basic XML documentation comments, and a minor breaking change in the removal of an unused public method which shouldn't have been included in the first place.

The [NuGet package](https://www.nuget.org/packages/Cyotek.Drawing.BitmapFont) has also been updated.

Regards;
Richard Moss
